apiVersion: v1
kind: Service
metadata:
  name: metastore-db
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore-db
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: damianbarsotti/spark-metastore-mysql:8.0.31
        name: metastore-db
        env:
        - name: MYSQL_DATABASE
          value: metastore
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        ports:
        - containerPort: 3306
          name: mysql
